### ISSUE TITLE
NET8 container does not start in Azure App Service, NET7 container does

### ISSUE THREAD

**Issue by mdddev** [dotnet/sdk-container-builds#423] opened 2023-04-21 11:08 UTC
Hi,

I am starting of a stock Visual Studio Web API Project. I have two of these one targeting NET7 and one targeting NET8. 

Both container images were built using `dotnet publish --os linux --arch x64 -p:PublishProfile=DefaultContainer -c Release` and pushed to my Azure Container Registry (I followed [this guidance](https://github.com/dotnet/sdk-container-builds/issues/422) for NET8 publish command).

I deployed both images to an App Service Plan using the Azure portal. The NET7 one works fine. The NET8 image does not. Here is a log exerpt showing the failure to start

```text
2023-04-20T20:13:18.612Z INFO  - Pulling image: myacr.azurecr.io/samples/webapi8:latest
2023-04-20T20:13:18.888Z INFO  - latest Pulling from samples/webapi8
2023-04-20T20:13:18.890Z INFO  -  Digest: sha256:somesha256digest
2023-04-20T20:13:18.890Z INFO  -  Status: Image is up to date for myacr.azurecr.io/samples/webapi8:latest
2023-04-20T20:13:18.892Z INFO  - Pull Image successful, Time taken: 0 Minutes and 0 Seconds
2023-04-20T20:13:18.931Z INFO  - Starting container for site
2023-04-20T20:13:18.931Z INFO  - docker run -d --expose=80 --name webapi8_0_899ae57f -e WEBSITES_ENABLE_APP_SERVICE_STORAGE=false -e WEBSITE_SITE_NAME=webapi8 -e WEBSITE_AUTH_ENABLED=False -e PORT=80 -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_HOSTNAME=webapi8.azurewebsites.net -e WEBSITE_INSTANCE_ID=someId -e WEBSITE_USE_DIAGNOSTIC_SERVER=False myacr.azurecr.io/samples/webapi8:latest  
2023-04-20T20:13:18.931Z INFO  - Logging is not enabled for this container.
Please use https://aka.ms/linux-diagnostics to enable logging to see container logs here.
2023-04-20T20:13:21.700Z INFO  - Initiating warmup request to container webapi8_0_899ae57f for site webapi8
2023-04-20T20:13:36.930Z INFO  - Waiting for response to warmup request for container webapi8_0_899ae57f. Elapsed time = 15.2300446 sec
2023-04-20T20:13:52.051Z INFO  - Waiting for response to warmup request for container webapi8_0_899ae57f. Elapsed time = 30.3504771 sec
2023-04-20T20:14:07.211Z INFO  - Waiting for response to warmup request for container webapi8_0_899ae57f. Elapsed time = 45.5111774 sec
2023-04-20T20:14:22.328Z INFO  - Waiting for response to warmup request for container webapi8_0_899ae57f. Elapsed time = 60.6273978 sec
2023-04-20T20:14:37.454Z INFO  - Waiting for response to warmup request for container webapi8_0_899ae57f. Elapsed time = 75.7537059 sec
2023-04-20T20:14:52.597Z INFO  - Waiting for response to warmup request for container webapi8_0_899ae57f. Elapsed time = 90.8964855 sec
2023-04-20T20:15:07.717Z INFO  - Waiting for response to warmup request for container webapi8_0_899ae57f. Elapsed time = 106.0168243 sec
2023-04-20T20:15:22.908Z INFO  - Waiting for response to warmup request for container webapi8_0_899ae57f. Elapsed time = 121.208133 sec
2023-04-20T20:15:38.030Z INFO  - Waiting for response to warmup request for container webapi8_0_899ae57f. Elapsed time = 136.3292715 sec
2023-04-20T20:15:53.408Z INFO  - Waiting for response to warmup request for container webapi8_0_899ae57f. Elapsed time = 151.7078356 sec
2023-04-20T20:16:08.547Z INFO  - Waiting for response to warmup request for container webapi8_0_899ae57f. Elapsed time = 166.8467398 sec
2023-04-20T20:16:23.775Z INFO  - Waiting for response to warmup request for container webapi8_0_899ae57f. Elapsed time = 182.0748242 sec
2023-04-20T20:16:38.892Z INFO  - Waiting for response to warmup request for container webapi8_0_899ae57f. Elapsed time = 197.19161 sec
2023-04-20T20:16:54.026Z INFO  - Waiting for response to warmup request for container webapi8_0_899ae57f. Elapsed time = 212.3259074 sec
2023-04-20T20:17:09.158Z INFO  - Waiting for response to warmup request for container webapi8_0_899ae57f. Elapsed time = 227.4579474 sec
2023-04-20T20:17:12.225Z ERROR - Container webapi8_0_899ae57f for site webapi8 did not start within expected time limit. Elapsed time = 230.5249047 sec
2023-04-20T20:17:12.241Z ERROR - Container webapi8_0_899ae57f didn't respond to HTTP pings on port: 80, failing site start. See container logs for debugging.
2023-04-20T20:17:12.256Z INFO  - Stopping site webapi8 because it failed during startup.

```

I have checked the log for the NET7 container and it immediately starts. The docker run command in that case is equivalent.

Does somebody have any insights on why this is happening?

**Comment by vlada-shubina** [comment] 2023-04-26 14:46
This issue is a duplicate of https://github.com/dotnet/aspnetcore/issues/47259. with solution suggested in https://github.com/dotnet/aspnetcore/issues/47259#issuecomment-1479972745. Please let us know if it works in for your case.

**Comment by baronfel** [comment] 2023-08-09 19:44
Going to close this as it's part of the .NET 8 containers changes, not our tooling specifically.

**Closed by baronfel** 2023-08-09 19:44 UTC

**Comment by Vice95** [comment] 2024-06-13 12:27
I have a Linux app service running 3 workers (background service listening on the service bus to manage queues) in Docker containers. from the logs I see that after a few seconds of warmup docker is stopped and restarts after about 30 minutes.
`Container workerprod_0_b91336ac didn't respond to HTTP pings on port: 8000, failing site start. See container logs for debugging.` the port in the docker file is 8000 and WEBISITES_PORT is 8000. Why does this happen? Thanks
