### ISSUE TITLE
Publishing the container image directly to remote registry with -p:ContainerRegistry tag is slow

### ISSUE THREAD

**Issue by asankaf** [dotnet/sdk-container-builds#315] opened 2023-01-27 14:00 UTC
I have a couple of projects where I tried pushing the images directly to Azure Container Registry with `-p:ContainerRegistry` during `dotnet publish` as a part of my CI (To avoid hard dependency on docker cli). However, this approach took me almost 4 minutes compared to creating the docker images in the local docker daemon and pushing them manually to ACR in two steps (which took only 1 minute total). I will have around 26 such images I need to build and publish, it could take several minutes if I directly publish them into acr. Is this by design or am I missing something here?

**Comment by rainersigwald** [comment] 2023-01-27 16:32
Not exactly by design, and there is likely some improvement we can do here. We saw fairly unreliable uploads before we moved to uploading fairly small chunks and doing chunk retry, which improved reliability, but at some performance cost. We expect to tweak chunk size parameters and I expect we'll also try to build in better reporting of retries, to give us some clues about what is causing the slowness.

**Comment by baronfel** [comment] 2023-01-27 16:40
I'd also be interested in seeing the Dockerfile you're comparing from, and the [binarylog](https://aka.ms/binlog) from your attempts to use this tooling @asankaf - one thing I see folks accidentally hitting is shipping their app Self Contained. This happens implicitly when a Runtime Identifier is chosen (which we encourage here). The result of this is that you're sending a ~150MB layer instead of a much smaller layer with just your application's DLL + direct dependencies.

**Comment by asankaf** [comment] 2023-01-27 21:09
@baronfel I am not using a Dockerfile to build the images. Following are the two scenarios I tested on,

1. `dotnet publish-c Release --no-build /t:PublishContainer -p:ContainerImageName=<image_name> -p:ContainerBaseImage=<base_img> -p:ContainerImageTag=18021 -p:ContainerRegistry=<acr_address>`
2. _Step 1_: `dotnet publish-c Release --no-build /t:PublishContainer -p:ContainerImageName=<image_name> -p:ContainerImageTag=18021 -p:ContainerRegistry=<acr_address>`
   _Step 2_: docker tag <image_name>:18021 <acr_address>/<image_name>:18021
   _Step 3_: docker push <acr_address>/<image_name>:18021

Approach 1 took 4 mins (for 2 types of images)
Approach 2 took 1 min (for the same 2 types of images)

**Comment by baronfel** [comment] 2023-01-27 22:04
Thanks for the clarification - that's definitely not the kind of experience we want. @rainersigwald a couple thoughts that come to mind to give users some knobs to tweak:

* [easy] environment variable to set chunk size?
* [easy] environment variable to set chunked/non-chunked uploads?
* [easy] environment variable to set parallel/sequential uploads of chunks
* [hard] sliding-scale chunk uploads that increase in size over time until they start erroring out, backing off of that to whatever the local maxima is?

**Comment by baronfel** [comment] 2024-10-04 20:14
We've got knobs for all of these now, so closing until/unless we get more specific perf issues.

**Closed by baronfel** 2024-10-04 20:14 UTC
