### ISSUE TITLE
Error on publish when upload to aws ecr

### ISSUE THREAD

**Issue by funkel1989** [dotnet/sdk-container-builds#424] opened 2023-04-22 17:52 UTC
here is my web api csproj file:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>442160dc-b3fe-4c2a-93e2-ba5476d59be3</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>$(NoWarn);1591</NoWarn>
        <Platforms>AnyCPU;x64</Platforms>
    </PropertyGroup>

    <PropertyGroup>
        <ContainerRuntimeIdentifier>linux-x64</ContainerRuntimeIdentifier>
        <PublishProfile>DefaultContainer</PublishProfile>
        <SelfContained>true</SelfContained>
        <PublishTrimmed>true</PublishTrimmed>
        <ContainerImageName>frontlinecrm-api-dev</ContainerImageName>
        <ContainerBaseImage>mcr.microsoft.com/dotnet/aspnet:7.0</ContainerBaseImage>
        <ContainerRegistry>{{accountNumberHere}}.dkr.ecr.us-east-2.amazonaws.com</ContainerRegistry>
    </PropertyGroup>

    <ItemGroup>
        <ContainerPort Include="80" Type="tcp" />
        <ContainerPort Include="443" Type="tcp" />
        <ContainerPort Include="5000" Type="tcp" />
        <ContainerPort Include="8080" Type="tcp" />
        <ContainerPort Include="8443" Type="tcp" />
    </ItemGroup>

    <ItemGroup>
        <ContainerEnvironmentVariable Include="ASPNETCORE_ENVIRONMENT" Value="dev" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.5" />
        <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="7.0.5" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="5.0.0" />
        <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="2.3.2" />
        <PackageReference Include="Microsoft.NET.Build.Containers" Version="0.4.0" />
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.18.1" />
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Controllers\" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\DataAccess\DataAccess.csproj" />
        <ProjectReference Include="..\FrontlineCrm\FrontlineCrm.csproj" />
    </ItemGroup>

</Project>
```

I'm running command 

```shell
aws ecr get-login-password --region us-east-2 --profile admin | docker login --username AWS --password-stdin {{accountnumberhere}}.dkr.ecr.us-east-2.amazonaws.com

dotnet publish -c Release
```

i'm getting the following error:

```text
MSBuild version 17.5.1+f6fdcf537 for .NET
  Determining projects to restore...
  Restored D:\code\git\battleline\FrontlineCrm.Api\FrontlineCrm\FrontlineCrm.csproj (in 214 ms).
  Restored D:\code\git\battleline\FrontlineCrm.Api\DataAccess\DataAccess.csproj (in 214 ms).
  Restored D:\code\git\battleline\FrontlineCrm.Api\FrontlineCrm.Api\FrontlineCrm.Api.csproj (in 214 ms).
  Restored D:\code\git\battleline\FrontlineCrm.Api\UnitTests\UnitTests.csproj (in 219 ms).

  FrontlineCrm -> D:\code\git\battleline\FrontlineCrm.Api\FrontlineCrm\bin\Release\net7.0\FrontlineCrm.dll
  FrontlineCrm -> D:\code\git\battleline\FrontlineCrm.Api\FrontlineCrm\bin\Release\net7.0\publish\
  DataAccess -> D:\code\git\battleline\FrontlineCrm.Api\DataAccess\bin\Release\net7.0\DataAccess.dll
  DataAccess -> D:\code\git\battleline\FrontlineCrm.Api\DataAccess\bin\Release\net7.0\publish\

FrontlineCrm.Api -> D:\code\git\battleline\FrontlineCrm.Api\FrontlineCrm.Api\bin\Release\net7.0\FrontlineCrm.Api.dll
  FrontlineCrm.Api -> D:\code\git\battleline\FrontlineCrm.Api\FrontlineCrm.Api\bin\Release\net7.0\publish\
  Building image 'frontlinecrm-api-dev' with tags 1.0.0 on top of base image mcr.microsoft.com:443/dotnet/aspnet:7.0
  Uploading layer sha256:26c5c85e47da3022f1bdb9a112103646c5c29517d757e95426f16e4bd9533405 to 139279799285.dkr.ecr.us-east-2.amazonaws.com
  Layer sha256:26c5c85e47da3022f1bdb9a112103646c5c29517d757e95426f16e4bd9533405 already existed
  Uploading layer sha256:6df469f23ae176b9dea89ebf6761b862c0721143da3bbd6303b953f6ab2091f1 to 139279799285.dkr.ecr.us-east-2.amazonaws.com
  Layer sha256:6df469f23ae176b9dea89ebf6761b862c0721143da3bbd6303b953f6ab2091f1 already existed
  Uploading layer sha256:d979c192027b10561ab55b8bb7150a0806f7a8fc474ee103e493e1e8f91c6e83 to 139279799285.dkr.ecr.us-east-2.amazonaws.com
  Layer sha256:d979c192027b10561ab55b8bb7150a0806f7a8fc474ee103e493e1e8f91c6e83 already existed
  Uploading layer sha256:cb22598f45ffaf5848df033c3fe01e897eecc2fb85734c36e186b301e36eece4 to 139279799285.dkr.ecr.us-east-2.amazonaws.com
  Layer sha256:cb22598f45ffaf5848df033c3fe01e897eecc2fb85734c36e186b301e36eece4 already existed
  Uploading layer sha256:0c210a47b91b24b22c1a3e0d9cd7da1b56f543394921b95b63094b336461ccb3 to 139279799285.dkr.ecr.us-east-2.amazonaws.com
  Layer sha256:0c210a47b91b24b22c1a3e0d9cd7da1b56f543394921b95b63094b336461ccb3 already existed
  Uploading layer sha256:49477f8612130a3632d0b269a6393ab35ffadc32b2085cdc83d1fca409cbfa0b to 139279799285.dkr.ecr.us-east-2.amazonaws.com
C:\Users\Michael\.nuget\packages\microsoft.net.build.containers\0.4.0\build\Microsoft.NET.Build.Containers.targets(195,5): error CONTAINER1013: Failed to push to the output registry: System.ApplicationException: CONTAI
NER1001: Failed to upload blob to PUT https://{{accountnumberhere}}.dkr.ecr.us-east-2.amazonaws.com/v2/frontlinecrm-api-dev/blobs/uploads/65f8daeb-b1d2-4fd4-aa46-39759ec82b53?&digest=sha256%3A49477f8612130a3632d0b269a6393ab35ff
adc32b2085cdc83d1fca409cbfa0b; received BadRequest with detail Docker-Distribution-Api-Version: registry/2.0 [D:\code\git\battleline\FrontlineCrm.Api\FrontlineCrm.Api\FrontlineCrm.Api.csproj]
C:\Users\Michael\.nuget\packages\microsoft.net.build.containers\0.4.0\build\Microsoft.NET.Build.Containers.targets(195,5): error CONTAINER1013: Sizes: 0.000000 [D:\code\git\battleline\FrontlineCrm.Api\FrontlineCrm.Api\
FrontlineCrm.Api.csproj]
C:\Users\Michael\.nuget\packages\microsoft.net.build.containers\0.4.0\build\Microsoft.NET.Build.Containers.targets(195,5): error CONTAINER1013: Date: Sat, 22 Apr 2023 17:43:16 GMT [D:\code\git\battleline\FrontlineCrm.A
pi\FrontlineCrm.Api\FrontlineCrm.Api.csproj]
C:\Users\Michael\.nuget\packages\microsoft.net.build.containers\0.4.0\build\Microsoft.NET.Build.Containers.targets(195,5): error CONTAINER1013:  [D:\code\git\battleline\FrontlineCrm.Api\FrontlineCrm.Api\FrontlineCrm.Ap
i.csproj]
C:\Users\Michael\.nuget\packages\microsoft.net.build.containers\0.4.0\build\Microsoft.NET.Build.Containers.targets(195,5): error CONTAINER1013: {"errors":[{"code":"BLOB_UPLOAD_INVALID","message":"None of the provided l
ayer digests match the calculated layer digest"}]} [D:\code\git\battleline\FrontlineCrm.Api\FrontlineCrm.Api\FrontlineCrm.Api.csproj]
C:\Users\Michael\.nuget\packages\microsoft.net.build.containers\0.4.0\build\Microsoft.NET.Build.Containers.targets(195,5): error CONTAINER1013: . [D:\code\git\battleline\FrontlineCrm.Api\FrontlineCrm.Api\FrontlineCrm.A
pi.csproj]
C:\Users\Michael\.nuget\packages\microsoft.net.build.containers\0.4.0\build\Microsoft.NET.Build.Containers.targets(195,5): error CONTAINER1013:    at Microsoft.NET.Build.Containers.Registry.FinishUploadSessionAsync(Str
ing digest, HttpClient client, UriBuilder uploadUri, CancellationToken cancellationToken) in D:\a\_work\1\s\Microsoft.NET.Build.Containers\Registry.cs:line 466 [D:\code\git\battleline\FrontlineCrm.Api\FrontlineCrm.Api\
FrontlineCrm.Api.csproj]
C:\Users\Michael\.nuget\packages\microsoft.net.build.containers\0.4.0\build\Microsoft.NET.Build.Containers.targets(195,5): error CONTAINER1013:    at Microsoft.NET.Build.Containers.Registry.UploadBlobAsync(String repos
itory, String digest, Stream contents, CancellationToken cancellationToken) in D:\a\_work\1\s\Microsoft.NET.Build.Containers\Registry.cs:line 490 [D:\code\git\battleline\FrontlineCrm.Api\FrontlineCrm.Api\FrontlineCrm.A
pi.csproj]
C:\Users\Michael\.nuget\packages\microsoft.net.build.containers\0.4.0\build\Microsoft.NET.Build.Containers.targets(195,5): error CONTAINER1013:    at Microsoft.NET.Build.Containers.Registry.PushAsync(Layer layer, Strin
g repository, Action`1 logProgressMessage, CancellationToken cancellationToken) in D:\a\_work\1\s\Microsoft.NET.Build.Containers\Registry.cs:line 332 [D:\code\git\battleline\FrontlineCrm.Api\FrontlineCrm.Api\FrontlineC
rm.Api.csproj]
C:\Users\Michael\.nuget\packages\microsoft.net.build.containers\0.4.0\build\Microsoft.NET.Build.Containers.targets(195,5): error CONTAINER1013:    at Microsoft.NET.Build.Containers.Registry.<>c__DisplayClass51_0.<<Push
Async>b__0>d.MoveNext() in D:\a\_work\1\s\Microsoft.NET.Build.Containers\Registry.cs:line 564 [D:\code\git\battleline\FrontlineCrm.Api\FrontlineCrm.Api\FrontlineCrm.Api.csproj]
C:\Users\Michael\.nuget\packages\microsoft.net.build.containers\0.4.0\build\Microsoft.NET.Build.Containers.targets(195,5): error CONTAINER1013: --- End of stack trace from previous location --- [D:\code\git\battleline\
FrontlineCrm.Api\FrontlineCrm.Api\FrontlineCrm.Api.csproj]
C:\Users\Michael\.nuget\packages\microsoft.net.build.containers\0.4.0\build\Microsoft.NET.Build.Containers.targets(195,5): error CONTAINER1013:    at Microsoft.NET.Build.Containers.Registry.PushAsync(BuiltImage builtIm
age, ImageReference source, ImageReference destination, Action`1 logProgressMessage, CancellationToken cancellationToken) in D:\a\_work\1\s\Microsoft.NET.Build.Containers\Registry.cs:line 581 [D:\code\git\battleline\Fr
ontlineCrm.Api\FrontlineCrm.Api\FrontlineCrm.Api.csproj]
C:\Users\Michael\.nuget\packages\microsoft.net.build.containers\0.4.0\build\Microsoft.NET.Build.Containers.targets(195,5): error CONTAINER1013:    at Microsoft.NET.Build.Containers.Tasks.CreateNewImage.ExecuteAsync(Can
cellationToken cancellationToken) in D:\a\_work\1\s\Microsoft.NET.Build.Containers\Tasks\CreateNewImage.cs:line 122 [D:\code\git\battleline\FrontlineCrm.Api\FrontlineCrm.Api\FrontlineCrm.Api.csproj]
```

Adding this here: https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_CompleteLayerUpload.html

**Comment by baronfel** [comment] 2023-05-01 18:08
@normj is there any chance you could get the ECR folks to give us some diagnostics from their end to help triage the problem? It's almost certain to be something we regressed, but I don't know where to start looking based on the errors we get directly from the API responses.

**Comment by normj** [comment] 2023-05-03 00:30
@baronfel I'll see what I can do

**Comment by vlada-shubina** [comment] 2023-05-04 14:03
@normj @baronfel 

I tried to investigate issues on our side. We have 2 issues at the moment. For the first I found workaround. 
Both are also reproducible on version that worked before (i tried the version from 15th Feb). 

First error occurs on `PATCH /v2/<name>/blobs/uploads/<uuid>` and happens due to `an existing connection was forcibly closed by the remote host`.  The workaround for this issue is to reduce chunk for upload (I checked with `1248080` bytes instead of current `5248080` bytes).

Second error occurs on finalizing the upload using `PUT /v2/<name>/blobs/uploads/<uuid>?digest=<digest>`. 
The returned error is `None of the provided layer digests match the calculated layer digest`, code: `BLOB_UPLOAD_INVALID`).
I haven't found a workaround for it.

The last successful push happened on 23rd March: https://github.com/baronfel/sdk-container-demo/actions/runs/4496866095/jobs/7911922863 using 0.4.0 version of the package. The version i tried is earlier and has the same problem now.

**Comment by normj** [comment] 2023-05-16 05:18
@baronfel @vlada-shubina Sorry I haven't been able to dedicate any time on helping this issue. I should have some time open up soon. I was able use the `containerize` console app in the `dotnet/sdk` repository and was able to successful push an image to ECR so I haven't recreated he issue locally yet for myself.

**Comment by vlada-shubina** [comment] 2023-05-23 14:55
> @baronfel @vlada-shubina Sorry I haven't been able to dedicate any time on helping this issue. I should have some time open up soon. I was able use the `containerize` console app in the `dotnet/sdk` repository and was able to successful push an image to ECR so I haven't recreated he issue locally yet for myself.

I can easily repro it on barebone web project on .NET SDK 7.0.302, steps to repro:
- login to AWS ECR with with get-login-password as described here: https://docs.aws.amazon.com/AmazonECR/latest/public/public-registries.html
- `dotnet new webapp` to create new web project
- add `<EnableSdkContainerSupport>true</EnableSdkContainerSupport>` property to csproj
- add `Properties\PublishProfiles\aws.pubxml` with the registry details (i'm using public registry here):
```
<Project>
    <PropertyGroup>
        <ContainerRegistry>public.ecr.aws</ContainerRegistry>
        <ContainerImageName>r4z9b1c4/sdk-containers-test</ContainerImageName>
        <WebPublishMethod>Container</WebPublishMethod>
    </PropertyGroup>
</Project>
```
- publish container using `dotnet publish --os linux --arch x64 -c Release /p:PublishProfile=aws`

**Comment by vlada-shubina** [comment] 2023-05-29 15:02
@normj 
I investigated it more:

- Error PATCH /v2/<name>/blobs/uploads/<uuid> due to an existing connection was forcibly closed by the remote host. The workaround for this issue of reducing the chunk to upload (I checked with 1248080 bytes instead of current 5248080 bytes) works reasonably well, i haven't encountered any issues so far after changing it, however it slows down the upload. Do you have any objections on changing the limit?
- Second error occurs on finalizing the upload using PUT /v2/<name>/blobs/uploads/<uuid>?digest=<digest>.
The returned error is None of the provided layer digests match the calculated layer digest, code: BLOB_UPLOAD_INVALID).

I noticed that in case of non-chunked upload it works as expected, when submitting digest of uncompressed content of the layer. For chunked upload it is not working with the error above. Should we submit anything else in this case?  

Thanks

**Comment by baronfel** [comment] 2023-05-30 20:07
That's very interesting - we have retries at a lower level (an HttpMessageHandler I believe) but the really interesting thing I see here is that they have an 'adaptive' chunk size. That's something I think we _need_ here, since our chunk sizes have been very fragile.

**Comment by normj** [comment] 2023-05-30 20:18
If I'm understanding correctly this library is only doing retries for `SocketException`. A mismatch on the digest would not be retried. The linked library does retries regardless of the type of errors. So my speculation is if there is an eventual consistency on the ECR side with putting the chuck and getting the digest that is not being retried. I don't know exactly how ECR is implemented but I'm sure S3 is involved at some point which is an eventual consistent store.

https://github.com/dotnet/sdk/blob/d03535e2d65c270b05ef6f4893330eb1cda4d9a9/src/Containers/Microsoft.NET.Build.Containers/AuthHandshakeMessageHandler.cs#L194

**Comment by baronfel** [comment] 2023-05-30 20:58
That's a great idea. After digging into that code a bit more I see that they _also_ use a `GET` on the blob upload endpoint to get the status of the upload (via the `Range` header there) in case some data needs to be re-sent. We should try to do the same.

**Comment by baronfel** [comment] 2023-05-31 03:54
@vlada-shubina I've made some progress on this based on the data @normj sent: https://github.com/dotnet/sdk/compare/release/7.0.4xx...baronfel:sdk:containers-chunk-retry?expand=1

So far the main changes are
* retries on chunk uploads specifically, and
* using the Range information from server requests to determine where the next chunk should start from

both are inspired from the regclient code linked. This worked well for github, GCP, and Azure chunked uploads.  For AWS uploads, each PATCH for a chunk, say the 0-63999 chunk, would return successfully but the `Range` information reported by ECR would remain `0-63999` across every iteration of chunks - we expect this number to climb as chunks are committed, and so we loop (forever?). I didn't see how the regclient codebase deals with this.

**Comment by baronfel** [comment] 2023-06-01 01:10
Found a bit more information today:
* when we start an upload, registries can potentially tell us what their chunk sizes are, so we [listen to them now](https://github.com/dotnet/sdk/compare/release/7.0.4xx...baronfel:sdk:containers-chunk-retry?expand=1#diff-b05a3261b9d87b9a41e5bf85618a08866eade0c80758092a747b4688b90c8622R544). AWS is one of these, but sometimes registries lie and report `0-0` ranges, so we handle that.
* I added the thing where we try a full upload and if that fails try a chunk upload: [dotnet/sdk@`release/7.0.4xx...baronfel:sdk:containers-chunk-retry?expand=1`#diff-b05a3261b9](https://github.com/dotnet/sdk/compare/release/7.0.4xx...baronfel:sdk:containers-chunk-retry?expand=1#diff-b05a3261b9d87b9a41e5bf85618a08866eade0c80758092a747b4688b90c8622R566-R583). That's kinda cool.
* I computed the digest from in-line with the chunks, in case it was different somehow than the other digests we had - they weren't :(
* I added more logging that I'll back out at some point - this was a little helpful

I still don't have a reason for the PUT failing on AWS uploads, but I was able to rule out digest mismatches at least.

**Comment by normj** [comment] 2023-06-01 07:36
@baronfel  I was doing some experimenting with your branch. The authentication logic in `AuthHandshakeMessageHandler` is to cache the authentication header for every request uri. Since new locations are vended all the time with new guids there is always a cache miss. So while doing a PATCH chunk 10MB upload of a layer the first attempt is done unauthenticated. I suspect ECR is thinking why are you sending me 10MB of unauthenticated data and so rejects the requests and shutdowns the socket. Hence all of the Socket forced closed exceptions.

As a quick hack I changed the authentication header cache in `AuthHandshakeMessageHandler` to use just the host name. Not saying that is the right solution but it works for ECR since the host name is what identifies registry that was logged in. When I did that my uploads seemed to work quite while without any socket forced closed exceptions. @baronfel Could you try recreating my hack and seeing if you are seeing similar behavior? Basically in the calls to `AuthHeaderCache` I changed the key to `new Uri("https://" + request.RequestUri.Host)` as a hack.

**Comment by baronfel** [comment] 2023-06-02 14:47
@normj I tried that as well and didn't have much success - the case you're describing (single Patch with 10MB upload) is the non-chunked upload, which is what we do when the default chunk size (or the chunk size reported by the registry) is greater than the size of the layer. This is the case that we knew worked before with AWS, the one-and-done method. The chunked method still fails for me using this proposed change - I forced the chunking by using `SDK_CONTAINER_REGISTRY_CHUNKED_UPLOAD: true` and `SDK_CONTAINER_REGISTRY_CHUNKED_UPLOAD_SIZE_BYTES: 1000` (or something equally small), and you can see the results in [this job](https://github.com/baronfel/sdk-container-demo/actions/runs/5146772468/jobs/9266282278).

I do think you have a point about the auth cache, though - the intent of that cache is to track authentication by host + repository, because each repository can have different credentials (the config json might have separate entries for `ghcr.io` and `ghcr.io/baronfel/sdk-container-demo`, for example). In addition, we should be caching by authentication method as well (Bearer, Basic, etc) and we're not doing that.  So some work should be done here overall (and TBH I'm not convinced that the current catch-all authentication handler is the correct place to put this, as it has no knowledge of registry and repository).

**Comment by baronfel** [comment] 2023-06-02 21:26
I finally figured out how to get logs out of my AWS ECR from CloudTrail, and it was embarrassingly easy to do:

>     "errorCode": "LayerPartTooSmallException",
>     "errorMessage": "All layer parts except the last part should be at least 5MB",

So I made a change to 

a) add a multi-MB lorem ipsum file to the app to bloat its size so that we're over the ECR-provided layer max size, and
b) re-introduced the ECR-specific 5MB check that I'd blown away

this made the chunked uploads work! Here's some debug logging showing the best of all worlds: an initial full-layer push, reacting to errors by moving to chunking, and finally chunking working!

```
Started upload session for sha256:f618f4d784e8b2c2851cafc0857d673746a8b1745807b7f42e8e54e329fbd9c2 to https://***.dkr.ecr.us-east-1.amazonaws.com:443/v2/sdk-container-demo/blobs/uploads/a3d7e2d0-7344-4962-9117-3498eccef9c6 with chunk size '5242880'
  Chunk size was greater than content length of 9340827, uploading whole blob.
Encountered a SocketException with message "Broken pipe". Pausing before retry.
Encountered a SocketException with message "Broken pipe". Pausing before retry.
Encountered a SocketException with message "Broken pipe". Pausing before retry.
Encountered a SocketException with message "Broken pipe". Pausing before retry.
Encountered a SocketException with message "Broken pipe". Pausing before retry.
  Errored while uploading whole blob: CONTAINER1006: Too many retries, stopping..
  Retrying with chunked upload.
  Processing chunk because (0 < 9340827)
  Processing chunk because (5242880 < 9340827)
  Uploaded content for sha256:f618f4d784e8b2c2851cafc0857d673746a8b1745807b7f42e8e54e329fbd9c2
  Computed digest for 'sha256:f618f4d784e8b2c2851cafc0857d673746a8b1745807b7f42e8e54e329fbd9c2' was 'sha256:f618f4d784e8b2c2851cafc0857d673746a8b1745807b7f42e8e54e329fbd9c2'
  Finalized upload session for sha256:f618f4d784e8b2c2851cafc0857d673746a8b1745807b7f42e8e54e329fbd9c2
  Finished uploading layer sha256:f618f4d784e8b2c2851cafc0857d673746a8b1745807b7f42e8e54e329fbd9c2 to ***.dkr.ecr.us-east-1.amazonaws.com
```

I'm a little irked that it was so easy to find logs in CloudTrail :sweat: I need to figure out how/why I regressed Google Cloud and Quay.io support (@tmds - any idea who we can talk to for more detailed logs at Quay?) then I'll work on cleaning this all up and documenting.

**Comment by normj** [comment] 2023-06-02 21:52
@baronfel Awesome! You are now the expert of AWS.

I didn't realize the refactoring took out the 5MB part size. If you add the hack I did for the authentication does the SocketExceptions go away?

**Comment by baronfel** [comment] 2023-06-03 18:05
@normj I'll check that next - I focused first on making quay and GCP work. 

I have greened those up by changing the upload algorithm a bit - before we defaulted to chunked mode if the chunk size detected from the registry was smaller than the blob's length. Quay and GCP don't actually give us a signal here one way or the other, so instead I changed to try the 'full' upload if no signal from the registry is detected, or a signal is detected and that length is greater than the blob. You can see this in action (heh) here: https://github.com/baronfel/sdk-container-demo/actions/runs/5164957782/jobs/9304177385

**Comment by baronfel** [comment] 2023-06-03 19:03
All green! (including harbor!)

https://github.com/baronfel/sdk-container-demo/actions/runs/5164957782

@normj I couldn't replicate the socket errors - in this run you can see there was only one socket failure and the overall 'full push' did work. This is the kind of behavior that I'd hope for.

Now will work on refactoring, in-repo tests, more sdk-container-demo test cases, docs, etc.

**Comment by tmds** [comment] 2023-06-05 16:02
> I need to figure out how/why I regressed Google Cloud and Quay.io support (@tmds - any idea who we can talk to for more detailed logs at Quay?

I've asked the question and I'll get back to you. I've also asked if there's a container image that can be used to run it locally.

If you log some specific issues for quay.io, you can cc me on them. I may take a look as well (if time permits).

**Comment by baronfel** [comment] 2023-06-05 16:04
@tmds false alarm - it was my fault. quay.io returns a Range header of `0--1` on the initial upload create, which crashed us. With some additional validation we're all good to go and greened up again.

I'll be adding tests to the linked PR to mimic behaviors of different registries (in terms of what their responses look like to different request patterns) to help ensure we don't regress.

**Comment by vlada-shubina** [comment] 2023-07-04 11:35
This was fixed by https://github.com/dotnet/sdk/pull/33500, mainly by uploading layers atomically. There is still an issue with chunked upload for AWS. I will create separate issue for that.

**Closed by vlada-shubina** 2023-07-04 11:35 UTC
Labels: bug, Priority: High, Iteration:2023May, Status:InProgress, size:8, Iteration:2023June
