### ISSUE TITLE
Support for hosted blazor wasm app?

### ISSUE THREAD

**Issue by ziaulhasanhamim** [dotnet/sdk-container-builds#259] opened 2022-11-25 12:46 UTC
I was trying to containerize an asp.net core app which was also hosting a blazor wasm app. But things doesn't seem to work.
I got this compilation error
```
C:\Program Files\dotnet\sdk\7.0.100\Sdks\Microsoft.NET.ILLink.Tasks\build\Microsoft.NET.ILLink.targets(196,5): error 
NETSDK1102: Optimizing assemblies for size is not supported for the selected publish configuration. Please ensure tha 
t you are publishing a self-contained app. [C:\Users\BlazeApp\Client\BlazeApp.Client.csproj]
```

**Comment by rainersigwald** [comment] 2022-11-28 18:07
Duplicate of #199

**Closed by rainersigwald** 2022-11-28 18:07 UTC
