### ISSUE TITLE
Custom image from dockerhub throws "'<' is an invalid start of a value"

### ISSUE THREAD

**Issue by SeppPenner** [dotnet/sdk-container-builds#293] opened 2023-01-16 10:31 UTC
I followed the tutorial from https://devblogs.microsoft.com/dotnet/announcing-builtin-container-support-for-the-dotnet-sdk/#comments and the container example from https://github.com/baronfel/sdk-container-demo. I was able to run the example project locally. However, if I just change the base image to a custom one from my dockerhub account, the following error occurs:

```log
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018: Unerwarteter Fehler bei der CreateNewImage-Aufgabe. [C:\Users\Nutzer\Documents
\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018: System.AggregateException: One or more errors occurred. ('<' is an invalid sta
rt of a value. LineNumber: 0 | BytePositionInLine: 0.) [C:\Users\Nutzer\Documents\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:  ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value
. LineNumber: 0 | BytePositionInLine: 0. [C:\Users\Nutzer\Documents\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& js
on, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes) [C:\Users\Nutzer\Documents\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker) [C:\Users\Nutz
er\Documents\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first) [C:\Users\Nut
zer\Documents\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at System.Text.Json.Utf8JsonReader.ReadSingleSegment() [C:\Users\Nutzer\Doc
uments\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at System.Text.Json.Utf8JsonReader.Read() [C:\Users\Nutzer\Documents\Temp\I
vu\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonRea
derOptions readerOptions, MetadataDb& database, StackRowStack& stack) [C:\Users\Nutzer\Documents\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at System.Text.Json.JsonDocument.ParseUnrented(ReadOnlyMemory`1 utf8Json, J
sonReaderOptions readerOptions, JsonTokenType tokenType) [C:\Users\Nutzer\Documents\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at System.Text.Json.JsonDocument.ParseValue(ReadOnlyMemory`1 json, JsonDocu
mentOptions options) [C:\Users\Nutzer\Documents\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at System.Text.Json.Nodes.JsonNode.Parse(String json, Nullable`1 nodeOption
s, JsonDocumentOptions documentOptions) [C:\Users\Nutzer\Documents\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at Microsoft.NET.Build.Containers.Registry.GetImageManifest(String name, St
ring reference) in D:\Code\containers\Microsoft.NET.Build.Containers\Registry.cs:line 95 [C:\Users\Nutzer\Documents\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    --- End of inner exception stack trace --- [C:\Users\Nutzer\Documents\Temp\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCancel
edExceptions) [C:\Users\Nutzer\Documents\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotifi
cation) [C:\Users\Nutzer\Documents\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at Microsoft.NET.Build.Containers.Tasks.CreateNewImage.GetBaseImage() in D:
\Code\containers\Microsoft.NET.Build.Containers\CreateNewImage.cs:line 80 [C:\Users\Nutzer\Documents\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at Microsoft.NET.Build.Containers.Tasks.CreateNewImage.Execute() in D:\Code
\containers\Microsoft.NET.Build.Containers\CreateNewImage.cs:line 96 [C:\Users\Nutzer\Documents\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskE
xecutionHost.Execute() [C:\Users\Nutzer\Documents\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecuti
onHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\Users\Nutzer\Documents\sdk-container-demo\sdk-container-demo.csproj]
```

Dotnet version: 7.0.102
Microsoft.NET.Build.Containers version: 0.3.0-alpha.28.g4d6ad5fc5a

The dockerfile looks like this (Check https://hub.docker.com/layers/sepppenner/dotnet7base/1.0.0/images/sha256-8967e8316608a30b36c5e16353d94ebb9c1800c19a2d2695a76ad156263ebc27?context=explore as well):

```Dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app

RUN apt-get update
RUN apt-get install -y libc6-dev libicu-dev libharfbuzz0b libfontconfig1 libfreetype6

ENV ASPNETCORE_URLS="http://*:5000" \
ASPNETCORE_ENVIRONMENT="Production" \
DOTNET_RUNNING_IN_CONTAINER=true \
TZ=Europe/Berlin \
LANG=de_DE.UTF-8 \
LANGUAGE=${LANG} \
LC_ALL=${LANG}
```

The example project can be found under: https://github.com/SeppPenner/-sdk-container-demo-custom.

**Comment by baronfel** [comment] 2023-01-16 20:28
I did some digging into this today, and it's very interesting. Try setting your `ContainerBaseImage` to `registry-1.docker.io/sepppenner/dotnet7base:1.0.0` and see if that works.

Apparently the provenance of many of the docker hub image URLs has varied over time. `docker.io` returns 200 OK messages for the Registry API calls, but the content is `text/html` instead of the requested actual media types. This is the cause of the error you see above.  `index.docker.io` returns 503s for everything. `registry-1.docker.io` is the one that works as expected, at least in my local testing.

**Comment by baronfel** [comment] 2023-01-17 22:38
I'm going to close this because I've been able to work around this with the registry-1 URL mentioned above. I've added this to the documentation in #296 for future reference.

**Closed by baronfel** 2023-01-17 22:38 UTC

**Comment by SeppPenner** [comment] 2023-01-20 08:00
Hi @baronfel. Good to know. However, in my case, it doesn't work yet (Seems to be a configuration issue I guess?):

```log
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018: Unerwarteter Fehler bei der CreateNewImage-Aufgabe. [C:\Users\Nutzer\Documents
\Temp\Test\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018: System.AggregateException: One or more errors occurred. (Failed retrieving cre
dentials for "registry-1.docker.io": Failed to execute 'C:\Program Files\Docker\Docker\resources\bin\docker-credential-desktop.EXE get': [C:\Users\Nutzer\Documents\Temp\Test\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018: credentials not found in native keychain [C:\Users\Nutzer\Documents\Temp\Test\s
dk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018: ) [C:\Users\Nutzer\Documents\Temp\Test\sdk-container-demo\sdk-container-demo.cs
proj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:  ---> Microsoft.NET.Build.Containers.Credentials.CredentialRetrievalException:
 Failed retrieving credentials for "registry-1.docker.io": Failed to execute 'C:\Program Files\Docker\Docker\resources\bin\docker-credential-desktop.EXE get': [C:\Users\Nutzer\Documents\Temp\Test\sdk-container-demo\sdk-container-demo.csp
roj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018: credentials not found in native keychain [C:\Users\Nutzer\Documents\Temp\Test\s
dk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:  [C:\Users\Nutzer\Documents\Temp\Test\sdk-container-demo\sdk-container-demo.csp
roj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:  ---> Valleysoft.DockerCredsProvider.CredsNotFoundException: Failed to execute
 'C:\Program Files\Docker\Docker\resources\bin\docker-credential-desktop.EXE get': [C:\Users\Nutzer\Documents\Temp\Test\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018: credentials not found in native keychain [C:\Users\Nutzer\Documents\Temp\Test\s
dk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:  [C:\Users\Nutzer\Documents\Temp\Test\sdk-container-demo\sdk-container-demo.csp
roj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at Valleysoft.DockerCredsProvider.NativeStore.ExecuteCredHelper(String comm
and, String input) [C:\Users\Nutzer\Documents\Temp\Test\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at Valleysoft.DockerCredsProvider.NativeStore.GetCredentialsAsync(String re
gistry) [C:\Users\Nutzer\Documents\Temp\Test\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at Valleysoft.DockerCredsProvider.CredsProvider.GetCredentialsAsync(String
registry, IFileSystem fileSystem, IProcessService processService, IEnvironment environment) [C:\Users\Nutzer\Documents\Temp\Test\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at Microsoft.NET.Build.Containers.AuthHandshakeMessageHandler.GetAuthentica
tionAsync(String registry, String scheme, Uri realm, String service, String scope, CancellationToken cancellationToken) in D:\Code\containers\Microsoft.NET.Build.Containers\AuthHandshakeMessageHandler.cs:line 105 [C:\Users\Nutzer\Docume
nts\Temp\Test\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    --- End of inner exception stack trace --- [C:\Users\Nutzer\Documents\Temp\
Test\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at Microsoft.NET.Build.Containers.AuthHandshakeMessageHandler.GetAuthentica
tionAsync(String registry, String scheme, Uri realm, String service, String scope, CancellationToken cancellationToken) in D:\Code\containers\Microsoft.NET.Build.Containers\AuthHandshakeMessageHandler.cs:line 109 [C:\Users\Nutzer\Docume
nts\Temp\Test\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at Microsoft.NET.Build.Containers.AuthHandshakeMessageHandler.SendAsync(Htt
pRequestMessage request, CancellationToken cancellationToken) in D:\Code\containers\Microsoft.NET.Build.Containers\AuthHandshakeMessageHandler.cs:line 180 [C:\Users\Nutzer\Documents\Temp\Test\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage re
quest, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) [C:\Users\Nutzer\Documents\Temp\Test\sdk-container-de
mo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at Microsoft.NET.Build.Containers.Registry.GetImageManifest(String name, St
ring reference) in D:\Code\containers\Microsoft.NET.Build.Containers\Registry.cs:line 89 [C:\Users\Nutzer\Documents\Temp\Test\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    --- End of inner exception stack trace --- [C:\Users\Nutzer\Documents\Temp\
Test\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCancel
edExceptions) [C:\Users\Nutzer\Documents\Temp\Test\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotifi
cation) [C:\Users\Nutzer\Documents\Temp\Test\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at Microsoft.NET.Build.Containers.Tasks.CreateNewImage.GetBaseImage() in D:
\Code\containers\Microsoft.NET.Build.Containers\CreateNewImage.cs:line 80 [C:\Users\Nutzer\Documents\Temp\Test\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at Microsoft.NET.Build.Containers.Tasks.CreateNewImage.Execute() in D:\Code
\containers\Microsoft.NET.Build.Containers\CreateNewImage.cs:line 96 [C:\Users\Nutzer\Documents\Temp\Test\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskE
xecutionHost.Execute() [C:\Users\Nutzer\Documents\Temp\Test\sdk-container-demo\sdk-container-demo.csproj]
C:\Users\Nutzer\.nuget\packages\microsoft.net.build.containers\0.3.0-alpha.28.g4d6ad5fc5a\build\Microsoft.NET.Build.Containers.targets(116,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecuti
onHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [C:\Users\Nutzer\Documents\Temp\Test\sdk-container-demo\sdk-container-demo.csproj]
```

Any ideas on how to handle this maybe? Do I have to do a `docker login` in the CMD before?

**Comment by baronfel** [comment] 2023-01-20 12:02
Yes, you would need to 'docker login registry-1.docker.io' and provide a username and password before this would work.

**Comment by SeppPenner** [comment] 2023-02-23 10:23
Sorry for the late reply, it works after logging in with `docker login login registry-1.docker.io`.
