### ISSUE TITLE
Authenticating to ACR using az credentials / managed identity

### ISSUE THREAD

**Issue by mbkrafft** [dotnet/sdk-container-builds#454] opened 2023-06-02 11:45 UTC
Hi,

I'm trying to build and push images to an Azure Container Registry without having docker as an explicit dependency. The image is being built correctly, but pushing it to a remote registry is not working without an explicit `docker login`.

Ideally I would like to be able to auth and push the image to an ACR by using:
- the `az login` and `az acr login -n <registry>` commands locally 
- a managed identity in the ADO build agents

Any roadmap or potential workarounds for using the Azure Default Credentials to directly push to a private ACR specified by the `<ContainerRegistry>$(registryName)</ContainerRegistry>` property during `dotnet publish`?

**Comment by baronfel** [comment] 2023-06-02 14:38
Hi @mbkrafft - this is a duplicate of #425 which our team is currently investigating. We do want to support Managed Identity as a first-class options, and we do currently support authenticating to ACR using

* admin credentials,
* non-admin token credentials, and
* Azure OIDC credentials (using `az acr login`, per their docs on how to use this inside a CI pipeline)

You can see some examples of these methods on [this GitHub Actions run](https://github.com/baronfel/sdk-container-demo/actions/runs/5123783814/jobs/9214785474).

Thanks!

**Closed by baronfel** 2023-06-02 14:38 UTC

**Comment by mbkrafft** [comment] 2023-06-05 09:14
Sorry about the duplicate and thanks for the swift response. Will look into it!
